name: MultiContainer Deployment
on:
  push:
    branches:
      - main
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t theunrulydev/react-tests-image -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true theunrulydev/react-tests-image npm run test
 
      - run: docker build -t theunrulydev/client-server ./client
      - run: docker build -t theunrulydev/nginx-server ./nginx
      - run: docker build -t theunrulydev/node-server ./server
      - run: docker build -t theunrulydev/worker-server ./worker
 
      - run: docker push theunrulydev/client-server
      - run: docker push theunrulydev/nginx-server 
      - run: docker push theunrulydev/node-server
      - run: docker push theunrulydev/worker-server